### ISSUE TITLE
Struggling to Install on Windows

### ISSUE THREAD

**Issue by jletienne** [brooke-watson/BRRR#7]
Thanks for putting this together, would like to use it.  Currently having installation issues.

![brrr](https://user-images.githubusercontent.com/10469138/33946757-32ecf0e8-dfe8-11e7-9f6c-0da00636fc8e.PNG)

Any suggestions?

**Comment by brooke-watson** [comment]
Oh man. I am but a humble Mac user, so I don't know what's going on here. Have you used `install_github()` successfully on other packages? might also be worth posting your `sessionInfo()`. 

I'll label it as help wanted and maybe a fellow Windows user/general CS person can swoop in and tell you what's going on.

**Comment by jletienne** [comment]
Thanks I got it setup last night on my Mac no problem.  Here's my sessionInfo()

![image](https://user-images.githubusercontent.com/10469138/33948515-a96711dc-dfec-11e7-8199-97ae4e749d33.png)

**Comment by naupaka** [comment]
It looks to me like it is failing because you have a space in the name of one of your directories (a name that starts with 'My' and the path parser isn't able to handle that.

See for example https://github.com/hadley/devtools/issues/73

From [this suggestion](https://stackoverflow.com/q/37144856/3114071), it also looks like you could set your `R_LIBS_USER` to somewhere that doesn't have a space in the PATH and then it should work.

See also here:
https://groups.google.com/forum/#!topic/shinyapps-users/Ivtcje0ORYw

where they recommend that 
>The only solution I'm aware of is to uninstall R and reinstall it to C:\R-XXX\ not C:\Program Files\R-XXX.

**Comment by jletienne** [comment]
Thanks I reinstalled R and it works perfectly!
